### ISSUE TITLE
(cata) lua error 

### ISSUE THREAD

**Issue by crossfactioninstancedpvp** [Verubato/framesort#38] opened 2024-07-06 06:54 UTC
1x [ADDON_ACTION_BLOCKED] AddOn 'FrameSort' tried to call the protected function 'CompactRaidFrame3:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua"]:378: in function `CompactUnitFrame_UpdateVisible'
[string "@Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua"]:304: in function <Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua:302>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua"]:136: in function <Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua:59>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by Verubato** [comment] 2024-07-06 08:09
Is this when using the Secure or Traditional sorting mode?

**Comment by crossfactioninstancedpvp** [comment] 2024-07-06 10:16
Secure I believe. Not at pc atm. The first one at the top on the sorting method tab.

**Comment by Verubato** [comment] 2024-07-07 02:53
I have no idea how this happened.

The stack trace is Blizzard code so it probably meants FrameSort tainted the raid frames somehow which shouldn't happen when using Secure sort mode.

If it keeps happening please let me know as I need more clues!

**Comment by crossfactioninstancedpvp** [comment] 2024-07-10 04:56
happened again here, can't recall when. thank you.

1x [ADDON_ACTION_BLOCKED] AddOn 'FrameSort' tried to call the protected function 'CompactRaidGroup1Member2:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua"]:378: in function `CompactUnitFrame_UpdateVisible'
[string "@Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua"]:304: in function <Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua:302>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua"]:136: in function <Blizzard_UnitFrame/Wrath/CompactUnitFrame.lua:59>

Locals:
Skipped (In Encounter)

**Comment by Verubato** [comment] 2024-07-10 05:37
Are you using the hide player feature by chance?

**Comment by crossfactioninstancedpvp** [comment] 2024-07-10 06:28
> Are you using the hide player feature by chance?

I am not.

**Comment by Verubato** [comment] 2024-07-14 03:44
I've received more information about this from other users, it seems to happen when summoning a pet during combat.

**Comment by Verubato** [comment] 2024-07-15 01:49
Narrowed it down to the following line of code causing taint:

https://github.com/Verubato/framesort/blob/c9d73b57331b96d00a3fab2d233e02426b785111/src/Providers/Blizzard.lua#L238C1-L238C130

This issue is caused by a Blizzard bug in cata (issue doesn't happen in retail).

Have logged a bug report with blizzard for this: https://github.com/Stanzilla/WoWUIBugs/issues/596

In the meantime, I'm trying some workarounds to avoid taint but haven't found a solution yet.

**Comment by Verubato** [comment] 2024-07-15 09:20
Issue potentially fixed in latest release 6.6.7.

**Closed** 2024-07-24 08:14 UTC
