### ISSUE TITLE
lua error 

### ISSUE THREAD

**Issue by fireymerlin** [Verubato/framesort#32] opened 2023-10-22 00:10 UTC
With no other addons, and not in party, I'm getting:
1x FrameSort/Modules/Sorting/SecureInCombat.lua:1061: attempt to call method 'SetProtected' (a nil value)

**Comment by Verubato** [comment] 2023-10-22 03:14
Is this in Retail or Wotlk?

**Comment by Verubato** [comment] 2023-10-24 07:49
I believe this bug existed in 5.9.2a-12 and was fixed in 5.9.2a-13.
Shouldn't be happening in the latest release 6.0.3.
Feel free to re-open if it's still happening.

**Comment by Verubato** [comment] 2023-11-08 00:03
In reply to fireymerlin: Hmm strange, I'm not sure what is wrong. 
Could you try running these commands in the chat window and see if any print "bad"?

/run local name = "sArena"; local container = _G[name]; print(name, container and (container.IsProtected and "good" or "bad") or "good")

/run local name = "GladiusExPartyFrame"; local container = _G[name]; print(name, container and (container.IsProtected and "good" or "bad") or "good")

/run local name = "GladiusExArenaFrame"; local container = _G[name]; print(name, container and (container.IsProtected and "good" or "bad") or "good")

/run local name = "ElvUF_PartyGroup1"; local container = _G[name]; print(name, container and (container.IsProtected and "good" or "bad") or "good")

/run local name = "CompactPartyFrame"; local container = _G[name]; print(name, container and (container.IsProtected and "good" or "bad") or "good")

/run local name = "CompactRaidFrameContainer"; local container = _G[name]; print(name, container and (container.IsProtected and "good" or "bad") or "good")

/run local name = "CompactArenaFrame"; local container = _G[name]; print(name, container and (container.IsProtected and "good" or "bad") or "good")

**Comment by Verubato** [comment] 2023-11-08 07:01
Found the issue is only happening for wow vanilla/classic. 
Will fix it in the next release.

**Comment by Verubato** [comment] 2023-11-09 13:13
Fixed in 6.0.10.

**Closed by Verubato** 2023-11-09 13:13 UTC
Labels: bug
